media:
  input: public/images
  output: /images

content:
  - name: posts
    label: Posts
    path: src/pages/posts
    type: collection
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: description
        label: Description
        type: string
      - name: body
        label: Contenu
        type: rich-text
        options:
          media:
            input: public/images
            output: /images